/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaswingproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class Marksheet extends javax.swing.JFrame {

    /**
     * Creates new form Marksheet
     */
    private Connection con;
    private ResultSet rs;

    public Marksheet() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/studentdata", "root", "");
//here sonoo is database name, root is username and password
            rs = getAllRecords();
            disableSearch();

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void disableSearch() {
        seatNoTextField.setEditable(false);
        searchButton.setEnabled(false);
    }

    void enableSearch() {
        seatNoTextField.setEditable(true);
        searchButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        seatNoTextField = new javax.swing.JTextField();
        collegeCodeTextField = new javax.swing.JTextField();
        enorllTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cTheoryTextField = new javax.swing.JTextField();
        cPracticalTextField = new javax.swing.JTextField();
        pythonTheoryTextField = new javax.swing.JTextField();
        pythonPracticalTextField = new javax.swing.JTextField();
        javaTheoryTextField = new javax.swing.JTextField();
        javaPracticalTextField = new javax.swing.JTextField();
        dotNetTheoryTextField = new javax.swing.JTextField();
        dotNetPracticalTextField = new javax.swing.JTextField();
        divisionButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        divisionLabel = new javax.swing.JLabel();
        percentageLabel = new javax.swing.JLabel();
        resultLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        seachEnableCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Marksheet Form");

        jLabel2.setText("Name :");

        jLabel3.setText("Seat No. :");

        jLabel4.setText("College Code :");

        jLabel5.setText("Enrollment No. :");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Student Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(collegeCodeTextField)
                                .addComponent(enorllTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seatNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(collegeCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(enorllTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel6.setText("Theory And Practical Marks");

        jLabel7.setText("C language :");

        jLabel8.setText("Python :");

        jLabel9.setText("Java");

        jLabel10.setText(".Net");

        cTheoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTheoryTextFieldActionPerformed(evt);
            }
        });

        divisionButton.setText("Division");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Theory");

        jLabel12.setText("Practical");

        jLabel17.setText("Total :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(divisionButton))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pythonTheoryTextField)
                                    .addComponent(javaTheoryTextField)
                                    .addComponent(dotNetTheoryTextField)
                                    .addComponent(jLabel11)
                                    .addComponent(cTheoryTextField))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dotNetPracticalTextField)
                                    .addComponent(pythonPracticalTextField)
                                    .addComponent(cPracticalTextField)
                                    .addComponent(jLabel12)
                                    .addComponent(javaPracticalTextField))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTheoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPracticalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pythonTheoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pythonPracticalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(javaTheoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(javaPracticalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dotNetTheoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dotNetPracticalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(divisionButton)
                        .addComponent(jLabel17))
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Division :");

        jLabel14.setText("Percentage :");

        jLabel15.setText("Result :");

        searchButton.setText("Search by Seat No.");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        seachEnableCheckBox.setText("Enable Search");
        seachEnableCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachEnableCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(firstButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(previousButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nextButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clearButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(updateButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seachEnableCheckBox)
                                        .addGap(53, 53, 53)
                                        .addComponent(searchButton)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divisionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resultLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(percentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstButton)
                                .addComponent(previousButton)
                                .addComponent(nextButton)
                                .addComponent(lastButton)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divisionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
                    .addComponent(resultLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton)
                            .addComponent(saveButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(seachEnableCheckBox))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void cTheoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTheoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTheoryTextFieldActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        // TODO add your handling code here:

        double cth = Double.parseDouble(cTheoryTextField.getText());
        double javath = Double.parseDouble(javaTheoryTextField.getText());
        double pythonth = Double.parseDouble(pythonTheoryTextField.getText());
        double dotnetth = Double.parseDouble(dotNetTheoryTextField.getText());
        double cpra = Double.parseDouble(cPracticalTextField.getText());
        double javapra = Double.parseDouble(javaPracticalTextField.getText());
        double pythonpra = Double.parseDouble(pythonPracticalTextField.getText());
        double dotnetpra = Double.parseDouble(dotNetPracticalTextField.getText());
        double gt = cth + javath + pythonth + dotnetth + cpra + javapra + pythonpra + dotnetpra;
        totalLabel.setText(String.valueOf(gt));
        double percent = gt / 4;
        percentageLabel.setText(String.valueOf(percent));
        if (cth >= 28 && javath >= 28 && pythonth >= 28 && dotnetth >= 28 && cpra >= 8 && javapra >= 8 && pythonpra >= 8 && dotnetpra >= 8) {
            resultLabel1.setText("Pass");
        } else {
            resultLabel1.setText("Fail");
        }
        if (percent >= 60 && cth >= 28 && javath >= 28 && pythonth >= 28 && dotnetth >= 28 && cpra >= 8 && javapra >= 8 && pythonpra >= 8 && dotnetpra >= 8) {
            divisionLabel.setText("First");
        } else if (percent >= 45 && percent < 60 && cth >= 28 && javath >= 28 && pythonth >= 28 && dotnetth >= 28 && cpra >= 8 && javapra >= 8 && pythonpra >= 8 && dotnetpra >= 8) {
            divisionLabel.setText("Second");
        } else if (percent < 45 && cth >= 28 && javath >= 28 && pythonth >= 28 && dotnetth >= 28 && cpra >= 8 && javapra >= 8 && pythonpra >= 8 && dotnetpra >= 8) {
            divisionLabel.setText("Third");
        } else {
            divisionLabel.setText("*****");
        }
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "INSERT INTO `studendata`( `name`, `enroll`, `collcode`, "
                    + "`ctheory`, `javatheory`, `pythontheory`, `dotnetheory`, `percent`,"
                    + "`total`, `result`, `div`, `cpractical`, `javapractical`, `pythonpractical`, `dotnetpractical`) VALUES ('" + nameTextField.getText() + "',"
                    + "'" + enorllTextField.getText() + "','" + collegeCodeTextField.getText() + "','" + cTheoryTextField.getText() + "','"
                    + javaTheoryTextField.getText() + "','" + pythonTheoryTextField.getText() + "','"
                    + dotNetTheoryTextField.getText() + "','"
                    + percentageLabel.getText() + "','" + totalLabel.getText() + "','" + resultLabel1.getText()
                    + "','" + divisionLabel.getText() + "','" + cPracticalTextField.getText() + "','"
                    + javaPracticalTextField.getText() + "','" + pythonPracticalTextField.getText()
                    + "','" + dotNetPracticalTextField.getText() + "')";
            Statement stmt = con.createStatement();
            int i = stmt.executeUpdate(sql);
            System.out.println("Insert=" + i);
            if (i == 1) {
                JOptionPane.showMessageDialog(Marksheet.this, "Successfully Inserted.", "Alert", JOptionPane.WARNING_MESSAGE);

            }
            getAllRecords();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.first()) {
                //Display values
                nameTextField.setText(rs.getString("name"));
                seatNoTextField.setText(rs.getString("id"));
                enorllTextField.setText(rs.getString("enroll"));
                collegeCodeTextField.setText(rs.getString("collcode"));
                cTheoryTextField.setText("" + rs.getInt("ctheory"));
                javaTheoryTextField.setText("" + rs.getInt("javatheory"));
                pythonTheoryTextField.setText("" + rs.getInt("pythontheory"));
                dotNetTheoryTextField.setText("" + rs.getInt("dotnetheory"));
                percentageLabel.setText("" + rs.getDouble("percent"));
                totalLabel.setText("" + rs.getInt("total"));
                resultLabel1.setText(rs.getString("result"));
                divisionLabel.setText(rs.getString("div"));
                cPracticalTextField.setText("" + rs.getInt("cpractical"));
                javaPracticalTextField.setText("" + rs.getInt("javapractical"));
                pythonPracticalTextField.setText("" + rs.getInt("pythonpractical"));
                dotNetPracticalTextField.setText("" + rs.getInt("dotnetpractical"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:

        try {
            if (rs.last()) {
                //Display values
                nameTextField.setText(rs.getString("name"));
                seatNoTextField.setText(rs.getString("id"));
                enorllTextField.setText(rs.getString("enroll"));
                collegeCodeTextField.setText(rs.getString("collcode"));
                cTheoryTextField.setText("" + rs.getInt("ctheory"));
                javaTheoryTextField.setText("" + rs.getInt("javatheory"));
                pythonTheoryTextField.setText("" + rs.getInt("pythontheory"));
                dotNetTheoryTextField.setText("" + rs.getInt("dotnetheory"));
                percentageLabel.setText("" + rs.getDouble("percent"));
                totalLabel.setText("" + rs.getInt("total"));
                resultLabel1.setText(rs.getString("result"));
                divisionLabel.setText(rs.getString("div"));
                cPracticalTextField.setText("" + rs.getInt("cpractical"));
                javaPracticalTextField.setText("" + rs.getInt("javapractical"));
                pythonPracticalTextField.setText("" + rs.getInt("pythonpractical"));
                dotNetPracticalTextField.setText("" + rs.getInt("dotnetpractical"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lastButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.previous()) {

                //Display values
                nameTextField.setText(rs.getString("name"));
                seatNoTextField.setText(rs.getString("id"));
                enorllTextField.setText(rs.getString("enroll"));
                collegeCodeTextField.setText(rs.getString("collcode"));
                cTheoryTextField.setText("" + rs.getInt("ctheory"));
                javaTheoryTextField.setText("" + rs.getInt("javatheory"));
                pythonTheoryTextField.setText("" + rs.getInt("pythontheory"));
                dotNetTheoryTextField.setText("" + rs.getInt("dotnetheory"));
                percentageLabel.setText("" + rs.getDouble("percent"));
                totalLabel.setText("" + rs.getInt("total"));
                resultLabel1.setText(rs.getString("result"));
                divisionLabel.setText(rs.getString("div"));
                cPracticalTextField.setText("" + rs.getInt("cpractical"));
                javaPracticalTextField.setText("" + rs.getInt("javapractical"));
                pythonPracticalTextField.setText("" + rs.getInt("pythonpractical"));
                dotNetPracticalTextField.setText("" + rs.getInt("dotnetpractical"));
            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:

        try {

            if (rs.next()) {
                //Display values
                nameTextField.setText(rs.getString("name"));
                seatNoTextField.setText(rs.getString("id"));
                enorllTextField.setText(rs.getString("enroll"));
                collegeCodeTextField.setText(rs.getString("collcode"));
                cTheoryTextField.setText("" + rs.getInt("ctheory"));
                javaTheoryTextField.setText("" + rs.getInt("javatheory"));
                pythonTheoryTextField.setText("" + rs.getInt("pythontheory"));
                dotNetTheoryTextField.setText("" + rs.getInt("dotnetheory"));
                percentageLabel.setText("" + rs.getDouble("percent"));
                totalLabel.setText("" + rs.getInt("total"));
                resultLabel1.setText(rs.getString("result"));
                divisionLabel.setText(rs.getString("div"));
                cPracticalTextField.setText("" + rs.getInt("cpractical"));
                javaPracticalTextField.setText("" + rs.getInt("javapractical"));
                pythonPracticalTextField.setText("" + rs.getInt("pythonpractical"));
                dotNetPracticalTextField.setText("" + rs.getInt("dotnetpractical"));
            }
        } catch (Exception e) {
            System.out.println(e);
            try {
                rs.last();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "UPDATE `studendata` SET `name`='" + nameTextField.getText() + "'"
                    + ",`enroll`='" + enorllTextField.getText() + "',"
                    + "`collcode`='" + collegeCodeTextField.getText() + "',"
                    + "`ctheory`='" + cTheoryTextField.getText() + "',`javatheory`='" + javaTheoryTextField.getText() + "',"
                    + "`pythontheory`='" + pythonTheoryTextField.getText() + "',`dotnetheory`='" + dotNetTheoryTextField.getText() + "',"
                    + "`percent`='" + percentageLabel.getText() + "',`total`='" + totalLabel.getText() + "',"
                    + "`result`='" + resultLabel1.getText() + "',`div`='" + divisionLabel.getText() + "',"
                    + "`cpractical`='" + cPracticalTextField.getText() + "',`javapractical`='" + javaPracticalTextField.getText() + "',"
                    + "`pythonpractical`='" + pythonPracticalTextField.getText()
                    + "',`dotnetpractical`='" + dotNetPracticalTextField.getText()
                    + "' where id='" + seatNoTextField.getText() + "'";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);

            JOptionPane.showMessageDialog(Marksheet.this, "Successfully Updated.", "Alert", JOptionPane.WARNING_MESSAGE);
            clearData();
            getAllRecords();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM studendata "
                    + "WHERE id = '" + seatNoTextField.getText() + "'";
            stmt.executeUpdate(sql);

            JOptionPane.showMessageDialog(Marksheet.this, "Successfully Deleted.", "Alert", JOptionPane.WARNING_MESSAGE);
            clearData();
            getAllRecords();

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:

        clearData();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String QUERY = "SELECT * FROM studendata where id='" + seatNoTextField.getText() + "'";
        rs = null;
        try {
            Statement stmt = con.createStatement();
            rs = stmt.executeQuery(QUERY);
            if (rs.next()) {
                nameTextField.setText(rs.getString("name"));
                seatNoTextField.setText(rs.getString("id"));
                enorllTextField.setText(rs.getString("enroll"));
                collegeCodeTextField.setText(rs.getString("collcode"));
                cTheoryTextField.setText("" + rs.getInt("ctheory"));
                javaTheoryTextField.setText("" + rs.getInt("javatheory"));
                pythonTheoryTextField.setText("" + rs.getInt("pythontheory"));
                dotNetTheoryTextField.setText("" + rs.getInt("dotnetheory"));
                percentageLabel.setText("" + rs.getDouble("percent"));
                totalLabel.setText("" + rs.getInt("total"));
                resultLabel1.setText(rs.getString("result"));
                divisionLabel.setText(rs.getString("div"));
                cPracticalTextField.setText("" + rs.getInt("cpractical"));
                javaPracticalTextField.setText("" + rs.getInt("javapractical"));
                pythonPracticalTextField.setText("" + rs.getInt("pythonpractical"));
                dotNetPracticalTextField.setText("" + rs.getInt("dotnetpractical"));
            } else {
                JOptionPane.showMessageDialog(Marksheet.this, "Not Found seat="+seatNoTextField.getText(), "Alert", JOptionPane.WARNING_MESSAGE);

            }
            getAllRecords();
//                 disableSearch();
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    private void seachEnableCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachEnableCheckBoxActionPerformed
        // TODO add your handling code here:
        if (seachEnableCheckBox.isEnabled()) {
            enableSearch();
        } else {
            disableSearch();
        }
    }//GEN-LAST:event_seachEnableCheckBoxActionPerformed

    private void clearData() {
        nameTextField.setText("");
        seatNoTextField.setText("");
        enorllTextField.setText("");
        collegeCodeTextField.setText("");
        cTheoryTextField.setText("");
        javaTheoryTextField.setText("");
        pythonTheoryTextField.setText("");
        dotNetTheoryTextField.setText("");
        percentageLabel.setText("");
        totalLabel.setText("");
        resultLabel1.setText("");
        divisionLabel.setText("");
        cPracticalTextField.setText("");
        javaPracticalTextField.setText("");
        pythonPracticalTextField.setText("");
        dotNetPracticalTextField.setText("");
    }

    private ResultSet getAllRecords() {
        String QUERY = "SELECT * FROM studendata";
        rs = null;
        try {
            Statement stmt = con.createStatement();
            rs = stmt.executeQuery(QUERY);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marksheet.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marksheet.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marksheet.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marksheet.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marksheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cPracticalTextField;
    private javax.swing.JTextField cTheoryTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField collegeCodeTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JTextField dotNetPracticalTextField;
    private javax.swing.JTextField dotNetTheoryTextField;
    private javax.swing.JTextField enorllTextField;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField javaPracticalTextField;
    private javax.swing.JTextField javaTheoryTextField;
    private javax.swing.JButton lastButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel percentageLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField pythonPracticalTextField;
    private javax.swing.JTextField pythonTheoryTextField;
    private javax.swing.JLabel resultLabel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox seachEnableCheckBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField seatNoTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
